name: Playwright Tests

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests on ${{ matrix.browser }}
        run: |
          npx playwright test \
            --grep "@smoke" \
            --project=${{ matrix.browser }} \
            --trace=on-first-retry

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results-${{ matrix.browser }}
          path: allure-results
          retention-days: 7

      - name: Upload Playwright HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright-report
          retention-days: 7

  allure-report:
    needs: test
    runs-on: ubuntu-latest
    if: always()

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          path: allure-results1

      - name: Merge Results
        run: |
          mkdir merged-results
          find allure-results1 -type f -name "*.json" -exec cp {} merged-results/ \;

      - name: Generate Allure Report
        run: |
          rm -rf allure-report1
          npx allure generate merged-results -o allure-report1

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report1
          retention-days: 7

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4