name: Playwright Tests

on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests on ${{ matrix.browser }}
        run: |
          npx playwright test \
            --grep "@smoke" \
            --project=${{ matrix.browser }} \
            --trace=on-first-retry

      # Upload raw allure results from each browser
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results-${{ matrix.browser }}
          path: allure-results
          retention-days: 7

      # Keep Playwright HTML report too
      - name: Upload Playwright HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright-report
          retention-days: 7


  allure-report:
    needs: test
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      # Download all browser results
      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          path: allure-results

      # Merge results
      - name: Merge Results
        run: |
          mkdir merged-results
          find allure-results -type f -name "*.json" -exec cp {} merged-results/ \;

      - name: Generate Allure Report
        run: |
          rm -rf allure-report
          npx allure generate merged-results -o allure-report

      # Upload final merged report
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 7
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4